# fly.toml app configuration file generated for gifting-game on 2024-11-26T23:52:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gifting-game'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
